### ISSUE TITLE
Plugins fails for multiple prefixed rules

### ISSUE THREAD

**Issue by wmartins** [celiolatorraca/autoprefixer-tv#1]
cc @andrejr

While trying to use this plugin with multiple prefix rules, it fails for some scenarios with multiple `-PREFIX-property` rules. As details below.

### `input.css`

```css
.example{
    font-size:-webkit-calc((10vw + 10px));
    font-size:calc((10vw + 10px));
    line-height:-webkit-calc(20vw + 20px);
    line-height:calc(20vw + 20px);
}
```

### Expected

```css
.example{
    font-size:-webkit-calc((10vw + 10px));
}
.example{
    line-height:-webkit-calc(20vw + 20px);
}
.example{
    font-size:calc((10vw + 10px));
    line-height:calc(20vw + 20px);
}
```

### Current output

> Note the comments to see the difference

```css
.example{
    font-size:-webkit-calc((10vw + 10px));
}
.example{
    line-height:calc(20vw + 20px); /* This should be prefixed */
}
.example{
    font-size:calc((10vw + 10px));
    line-height:-webkit-calc(20vw + 20px); /* This should not be prefixed */
}
```

### `input.css`

```css
.example{
    font-size:-webkit-calc((10vw + 10px));
    font-size:calc((10vw + 10px));
    line-height:-webkit-calc(20vw + 20px);
    line-height:calc(20vw + 20px);
    max-height:-webkit-calc(30vw + 30px);
    max-height:calc(30vw + 30px);
}
```

### Expected

```css
.example{
    font-size:-webkit-calc((10vw + 10px));
}
.example{
    line-height:-webkit-calc(20vw + 20px);
}
.example{
    max-height:-webkit-calc(30vw + 30px);
}
.example{
    font-size:calc((10vw + 10px));
    line-height:calc(20vw + 20px);
    max-height:calc(30vw + 30px);
}
```

### Current output

Fails with:

```TypeError: Cannot read property 'prop' of undefined```

<details>
  <summary>Error details</summary>

  ```js
  TypeError: Cannot read property 'prop' of undefined

      at duplicatedProps.forEach.duplicatedProp (index.js:49:43)
          at Array.forEach (<anonymous>)
      at css.walkRules.rule (index.js:37:25)
      at node_modules/postcss/lib/container.js:237:28
      at node_modules/postcss/lib/container.js:144:26
      at Root.each (node_modules/postcss/lib/container.js:110:22)
      at Root.walk (node_modules/postcss/lib/container.js:143:21)
      at Root.walkRules (node_modules/postcss/lib/container.js:235:25)
      at css (index.js:32:9)
      at LazyResult.run (node_modules/postcss/lib/lazy-result.js:277:20)
      at LazyResult.asyncTick (node_modules/postcss/lib/lazy-result.js:192:32)
      at processing.Promise.then._this2.processed (node_modules/postcss/lib/lazy-result.js:231:20)
          at new Promise (<anonymous>)
      at LazyResult.async (node_modules/postcss/lib/lazy-result.js:228:27)
      at LazyResult.then (node_modules/postcss/lib/lazy-result.js:134:21)
      at run (tests/index.test.js:9:1)
      at Object.it.only (tests/index.test.js:44:16)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  ```
</details>
